################################
# Dockerfile: thedcg/pandoc-gentoo_prep1:latest

# ベース
FROM thedcg/tl-gentoo_prep8:latest

################################
# Dockerfile

# 管理者
#MAINTAINER Lemures Lemniscati <lemures.lemniscati@gmail.com>

# パッケージ
RUN date --iso-8601=ns\
 && emerge\
 dev-lang/ghc\
 app-admin/haskell-updater\
 dev-haskell/cabal\
 dev-haskell/transformers\
 dev-haskell/data-default-class\
 dev-haskell/network\
 dev-haskell/byteable\
 dev-haskell/syb\
 dev-haskell/old-locale\
 dev-haskell/stm\
 dev-haskell/binary\
 dev-haskell/zlib\
 dev-haskell/hourglass\
 dev-haskell/primitive\
 dev-haskell/random\
 dev-haskell/base64-bytestring\
 dev-haskell/deepseq-generics\
 dev-haskell/dlist\
 dev-haskell/bytestring-builder\
 dev-haskell/cereal\
 dev-haskell/split\
 dev-haskell/setenv\
 dev-haskell/rfc5051\
 dev-haskell/extensible-exceptions\
 dev-haskell/unix-compat\
 dev-haskell/digest\
 dev-haskell/utf8-string\
 dev-haskell/text\
 dev-haskell/mtl\
 dev-haskell/vector\
 dev-haskell/asn1-types\
 dev-haskell/securemem\
 dev-haskell/cryptohash\
 dev-haskell/old-time\
 dev-haskell/async\
 dev-haskell/hs-bibutils\
 dev-haskell/cmdargs\
 dev-haskell/data-default-instances-base\
 dev-haskell/data-default-instances-dlist\
 dev-haskell/data-default-instances-containers\
 dev-haskell/data-default-instances-old-locale\
 dev-haskell/sha\
 dev-haskell/haddock-library\
 dev-haskell/socks\
 dev-haskell/blaze-builder\
 dev-haskell/hashable\
 dev-haskell/parsec\
 dev-haskell/asn1-encoding\
 dev-haskell/transformers-compat\
 dev-haskell/crypto-random\
 dev-haskell/pem\
 dev-haskell/crypto-cipher-types\
 dev-haskell/data-default\
 dev-haskell/tagsoup\
 && date --iso-8601=ns\

# 終了
