################################
# Dockerfile: thedcg/pandoc-gentoo_prep2:latest

# ベース
FROM thedcg/pandoc-gentoo_prep1:latest

################################
# Dockerfile

# 管理者
#MAINTAINER Lemures Lemniscati <lemures.lemniscati@gmail.com>

# パッケージ
RUN date --iso-8601=ns\
 && emerge\
 dev-haskell/xml\
 dev-haskell/xml-types\
 dev-haskell/juicypixels\
 dev-haskell/cmark\
 dev-haskell/hslua\
 dev-haskell/zip-archive\
 dev-haskell/filemanip\
 dev-haskell/regex-base-0.93.2-r1
 dev-haskell/mime-types\
 dev-haskell/transformers-base\
 dev-haskell/unordered-containers\
 dev-haskell/crypto-pubkey-types\
 dev-haskell/scientific\
 dev-haskell/exceptions\
 dev-haskell/network-uri\
 dev-haskell/blaze-markup\
 dev-haskell/mmorph\
 dev-haskell/streaming-commons\
 dev-haskell/crypto-numbers\
 dev-haskell/case-insensitive\
 dev-haskell/nats\
 dev-haskell/asn1-parse\
 dev-haskell/cipher-aes\
 dev-haskell/cipher-rc4\
 dev-haskell/cipher-des\
 dev-haskell/regex-pcre-builtin\
 dev-haskell/cookie\
 dev-haskell/attoparsec\
 dev-haskell/monad-control\
 dev-haskell/x509\
 dev-haskell/blaze-html\
 dev-haskell/temporary\
 dev-haskell/http-types\
 dev-haskell/crypto-pubkey\
 dev-haskell/semigroups\
 dev-haskell/http\
 dev-haskell/aeson\
 dev-haskell/x509-store\
 dev-haskell/lifted-base-0.2.3.6-r2
 dev-haskell/http-client\
 dev-haskell/void\
 dev-haskell/highlighting-kate\
 dev-haskell/resourcet\
 dev-haskell/x509-validation\
 dev-haskell/aeson-pretty\
 dev-haskell/enclosed-exceptions\
 dev-haskell/x509-system\
 dev-haskell/conduit\
 dev-haskell/tls\
 dev-haskell/texmath\
 dev-haskell/yaml\
 dev-haskell/conduit-extra\
 dev-haskell/connection\
 dev-haskell/xml-conduit\
 dev-haskell/http-client-tls\
 && date --iso-8601=ns\

# 終了
