################################
# Dockerfile: thedcg/pandoc-gentoo_prep2:latest

# ベース
FROM thedcg/pandoc-gentoo_prep1:latest

################################
# Dockerfile

# 管理者
#MAINTAINER Lemures Lemniscati <lemures.lemniscati@gmail.com>

# パッケージ
RUN date --iso-8601=ns\
 && emerge\
 dev-haskell/cabal\
 dev-haskell/transformers\
 dev-haskell/data-default-class\
 dev-haskell/network\
 dev-haskell/byteable\
 dev-haskell/syb\
 dev-haskell/old-locale\
 dev-haskell/stm\
 dev-haskell/binary\
 dev-haskell/zlib\
 dev-haskell/hourglass\
 dev-haskell/primitive\
 dev-haskell/random\
 dev-haskell/base64-bytestring\
 dev-haskell/deepseq-generics\
 dev-haskell/dlist\
 dev-haskell/bytestring-builder\
 dev-haskell/cereal\
 dev-haskell/split\
 dev-haskell/setenv\
 dev-haskell/rfc5051\
 dev-haskell/extensible-exceptions\
 dev-haskell/unix-compat\
 dev-haskell/digest\
 dev-haskell/utf8-string\
 dev-haskell/text\
 dev-haskell/mtl\
 dev-haskell/vector\
 dev-haskell/asn1-types\
 dev-haskell/securemem\
 dev-haskell/cryptohash\
 dev-haskell/old-time\
 dev-haskell/async\
 dev-haskell/hs-bibutils\
 dev-haskell/cmdargs\
 dev-haskell/data-default-instances-base\
 dev-haskell/data-default-instances-dlist\
 dev-haskell/data-default-instances-containers\
 dev-haskell/data-default-instances-old-locale\
 dev-haskell/sha\
 dev-haskell/haddock-library\
 dev-haskell/socks\
 dev-haskell/blaze-builder\
 dev-haskell/hashable\
 dev-haskell/parsec\
 dev-haskell/asn1-encoding\
 dev-haskell/transformers-compat\
 dev-haskell/crypto-random\
 dev-haskell/pem\
 dev-haskell/crypto-cipher-types\
 dev-haskell/data-default\
 dev-haskell/tagsoup\
 dev-haskell/xml\
 dev-haskell/xml-types\
 dev-haskell/juicypixels\
 dev-haskell/cmark\
 dev-haskell/hslua\
 dev-haskell/zip-archive\
 dev-haskell/filemanip\
 dev-haskell/regex-base-0.93.2-r1
 dev-haskell/mime-types\
 dev-haskell/transformers-base\
 dev-haskell/unordered-containers\
 dev-haskell/crypto-pubkey-types\
 dev-haskell/scientific\
 dev-haskell/exceptions\
 dev-haskell/network-uri\
 dev-haskell/blaze-markup\
 dev-haskell/mmorph\
 dev-haskell/streaming-commons\
 dev-haskell/crypto-numbers\
 dev-haskell/case-insensitive\
 dev-haskell/nats\
 dev-haskell/asn1-parse\
 dev-haskell/cipher-aes\
 dev-haskell/cipher-rc4\
 dev-haskell/cipher-des\
 dev-haskell/regex-pcre-builtin\
 dev-haskell/cookie\
 dev-haskell/attoparsec\
 dev-haskell/monad-control\
 dev-haskell/x509\
 dev-haskell/blaze-html\
 dev-haskell/temporary\
 dev-haskell/http-types\
 dev-haskell/crypto-pubkey\
 dev-haskell/semigroups\
 dev-haskell/http\
 dev-haskell/aeson\
 dev-haskell/x509-store\
 dev-haskell/lifted-base-0.2.3.6-r2
 dev-haskell/http-client\
 dev-haskell/void\
 dev-haskell/highlighting-kate\
 dev-haskell/resourcet\
 dev-haskell/x509-validation\
 dev-haskell/aeson-pretty\
 dev-haskell/enclosed-exceptions\
 dev-haskell/x509-system\
 dev-haskell/conduit\
 dev-haskell/tls\
 dev-haskell/texmath\
 dev-haskell/yaml\
 dev-haskell/conduit-extra\
 dev-haskell/connection\
 dev-haskell/xml-conduit\
 dev-haskell/http-client-tls\
 && date --iso-8601=ns\

# 終了
